version: "3.6"
services:
  zipkin:
    ports:
      - "9411:9411"
    image: openzipkin/zipkin

  nginx:
    build: nginx/
    ports:
      - "8080:80"
    links:
      - php

  php:
    build: php/
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
