version: "3.6"
services:
  zipkin:
    ports:
      - "9411:9411"
    image: openzipkin/zipkin

  nginx:
    build: nginx/
    ports:
      - "8080:80"
    links:
      - php

  php:
    build: php/
  
  webapi:
    build: python/app/
    # サービス起動後に入力されるコマンドを設定
    # command: python manage.py runserver 0.0.0.0:8000
    command: uwsgi --socket :8081 --wsgi-file django_demo/wsgi.py --logto /tmp/uwsgi.log --py-autoreload 1
    # 環境変数を指定
    environment:
      # 1ならデバックモード
      - DEBUG=1
      # setting.pyに記載されているSECRET_KEYを記入
      - 'SECRET_KEY=oyux(%m0pa8(fc$$rns&jm$$$$o(nbta04eww2j34z2pwn9p!%e)%'
